version: "3.9"

networks:
    fiar_game:
        driver: bridge 

services:
    server:
      container_name: server
      image: <image_name> # образ из гитхаба
      restart: always
      ports:
        - "3000:3000"
      environment:
        SERVER_PORT: 3000
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
        POSTGRES_PORT: 5432
        POSTGRES_HOST: postgres
      tty: true
      networks:
        - fiar_game
      depends_on:
        postgres:
          condition: service_healthy

    postgres:
      container_name: db
      image: postgres:14     
      ports:
        - "5432:5432"
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
      volumes:
        - /var/lib/postgresql/data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 1s
        timeout: 5s
        retries: 10
      tty: true
      networks:
          - fiar_game

    pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4:4.18
      restart: always
      # PGADMIN_DEFAULT_EMAIL и PGADMIN_DEFAULT_PASSWORD вводить для авторизации на http://localhost:8080/browser/
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: secret
        PGADMIN_LISTEN_PORT: 80
      ports:
        - "8080:80"
      volumes:
        - /var/lib/pgadmin:/var/lib/pgadmin
      depends_on:
        - postgres
      networks:
        - fiar_game


