const COMMENT_LENGTH_MIN = 5
const COMMENT_LENGTH_MAX = 280
const USER_NAME_LENGTH_MIN = 3
const USER_NAME_LENGTH_MAX = 24
const TOPIC_NAME_LENGTH_MIN = 3
const TOPIC_NAME_LENGTH_MAX = 32

export {
  USER_NAME_LENGTH_MIN,
  USER_NAME_LENGTH_MAX,
  COMMENT_LENGTH_MIN,
  COMMENT_LENGTH_MAX,
  TOPIC_NAME_LENGTH_MIN,
  TOPIC_NAME_LENGTH_MAX,
}
